#lang brag
TOP_CONFIG : CONST_EXPR | ENUM_EXPR | STRUCT_EXPR | INCLUDE_EXPR

CONST_EXPR : "const" IDENTIFIER "=" ANY_VALUE
ENUM_EXPR : "enum" IDENTIFIER "{" ENUM_MEMBER* (COMMA ENUM_MEMBER)* "}"
STRUCT_EXPR : "struct" IDENTIFIER "{" STRUCT_MEMBER_LINE* NEWLINE* "}"
INCLUDE_EXPR : "%#include" FILE_PATH


ENUM_MEMBER : IDENTIFIER "=" ANY_VALUE
STRUCT_MEMBER_LINE : NEWLINE STRUCT_MEMBER
STRUCT_MEMBER : IDENTIFIER IDENTIFIER SEMICOLON
FILE_PATH : STRING

ANY_VALUE : NUMBER

